version: "1"

services:

  jwt_back_app:
    build:
        context: ./back/
    container_name: jwt-back-app
    ports:
      - 8008:8000
    restart: always
    stdin_open: true
    tty: true
    depends_on:
      jwt_db:
        condition: service_healthy

  jwt_db:
    build:
      context: ./back/db/
    container_name: jwt-db
    environment:
      POSTGRES_HOST: "jwt_db"
      POSTGRES_DB: "test_jwt_db"
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      SECRET_KEY: ${SECRET_KEY}
    env_file:
      - ./.env
    ports:
      - "5435:5432"
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d test_jwt_db -U jwt" ]
      interval: 5s
      timeout: 5s
      retries: 5

  jwt_nginx_app:
    image: nginx:latest
    container_name: jwt-nginx-app
    ports:
      - 87:80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jwt.rule=Host(`jwt.tesseractmaks.tech`)"
    restart: always
    volumes:
      - ./back/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      jwt_back_app:
        condition: service_started

volumes:
  pg_jwt_db:

networks:
  default:
    name: proxynet
    external: true
